name: alfred
description: A performant, expressjs like server framework with a few bonuses that make life even easier.
version: 0.1.0-alpha.3
repository: https://github.com/rknell/alfred

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http_server: ^1.0.0
  mime_type: ^1.0.0
  enum_to_string: ^2.0.1
  queue: ^3.0.0-nullsafety.0
  pedantic: ^1.9.0

dev_dependencies:
  test: ^1.14.4
  http: