name: webserver
description: High performance expressjs like webserver for dart.
version: 0.0.1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http_server: ^1.0.0
  uri: ^1.0.0
  mime_type: ^1.0.0
  enum_to_string:

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
  http:
